title: Bubble Overview
resources:
- url: /hacsfiles/Bubble-Card/bubble-card.js
  type: module
- url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  type: module
views:
- title: Overview
  path: overview
  icon: mdi:home
  theme: default
  cards:
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.living_room
    name: Living Room
    icon: mdi:sofa
    show_state: true
    show_last_changed: false
    show_attribute: true
    attribute: brightness
    slider_live_update: false
    allow_light_slider_to_0: false
    card_layout: large
    sub_button:
    - icon: mdi:arrow-expand
      name: ''
      tap_action:
        action: navigate
        navigation_path: '#living-room-lights'
      show_background: true
  - type: vertical-stack
    cards:
    - type: custom:bubble-card
      card_type: pop-up
      hash: '#living-room-lights'
      name: Living Room Lights
      icon: mdi:sofa
      back_open: false
      close_by_clicking_outside: true
      bg_opacity: '88'
      bg_blur: '14'
      margin_top_mobile: '0'
      margin_top_desktop: '0'
      width_desktop: 540px
      is_sidebar_hidden: false
      auto_close: 60000
    - type: custom:bubble-card
      card_type: separator
      name: Room Control
      icon: mdi:lightbulb-group
    - type: custom:bubble-card
      card_type: button
      button_type: slider
      entity: light.living_room
      name: All Lights
      icon: mdi:lightbulb-group
      show_state: true
      show_attribute: true
      attribute: brightness
      slider_live_update: false
      allow_light_slider_to_0: true
      sub_button:
      - entity: light.living_room
        icon: mdi:palette
        name: Color
        tap_action:
          action: more-info
    - type: custom:bubble-card
      card_type: separator
      name: Hue Scenes
      icon: mdi:palette
    - type: custom:auto-entities
      card:
        type: grid
        columns: 4
        square: false
      card_param: cards
      filter:
        template: |-
          {% set scenes = states.scene | selectattr('entity_id', 'match', 'scene.living_room_') | list %}
          {% for scene in scenes | sort(attribute='attributes.friendly_name') %}
            {%- set scene_name = scene.attributes.friendly_name | replace('Living Room ', '') | replace('Living room ', '') -%}
            {%- set icon_map = {
              'USA': 'mdi:flag',
              'Read': 'mdi:book-open',
              'Ruby glow': 'mdi:fire',
              'Dimmed': 'mdi:brightness-3',
              'Bright': 'mdi:brightness-7',
              'Concentrate': 'mdi:target',
              'Energize': 'mdi:lightning-bolt',
              'Relax': 'mdi:spa',
              'Nightlight': 'mdi:weather-night',
              'Halloween': 'mdi:halloween',
              'Xmas': 'mdi:pine-tree',
              'Arctic aurora': 'mdi:aurora',
              'Spring blossom': 'mdi:flower',
              'Tropical twilight': 'mdi:palm-tree',
              'Savanna sunset': 'mdi:weather-sunset',
              'Nebula': 'mdi:creation',
              'Rainbow': 'mdi:looks',
              'Ibiza': 'mdi:party-popper',
              'Sweden': 'mdi:flag',
              'Sunday morning': 'mdi:coffee',
              'Champagne': 'mdi:glass-flute',
              'Lavender': 'mdi:flower-outline',
              'Peach': 'mdi:fruit-cherries',
              'Circle': 'mdi:circle',
              'Blue white': 'mdi:snowflake'
            } -%}
            {%- set icon = icon_map.get(scene_name, 'mdi:palette') -%}
            {
              "type": "custom:bubble-card",
              "card_type": "button",
              "button_type": "name",
              "name": "{{ scene_name }}",
              "icon": "{{ icon }}",
              "entity": "{{ scene.entity_id }}",
              "card_layout": "normal",
              "styles": "ha-card { height: 36px !important; } .bubble-container { height: 36px !important; } .bubble-name { font-size: 11px !important; } .bubble-icon-container { min-width: 28px !important; min-height: 28px !important; margin: 4px !important; } .bubble-icon { --mdc-icon-size: 18px !important; }",
              "button_action": {
                "tap_action": {
                  "action": "call-service",
                  "service": "scene.turn_on",
                  "service_data": {
                    "entity_id": "{{ scene.entity_id }}"
                  }
                }
              }
            }{%- if not loop.last -%},{%- endif -%}
          {% endfor %}
    - type: custom:bubble-card
      card_type: separator
      name: Individual Lights
      icon: mdi:lightbulb
    - type: custom:auto-entities
      card:
        type: vertical-stack
      card_param: cards
      filter:
        include:
        - area: Living Room
          domain: light
          options:
            type: custom:bubble-card
            card_type: button
            button_type: slider
            show_state: true
            show_attribute: true
            attribute: brightness
            slider_live_update: false
            allow_light_slider_to_0: true
        exclude:
        - entity_id: light.living_room
      sort:
        method: friendly_name
