# Simple test without auto-entities to isolate the error
resources:
  - url: /local/community/Bubble-Card/bubble-card.js
    type: module

title: Test Dashboard
views:
  - title: Test
    path: test
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: light.living_room
        name: Test Button